services:
  - type: web
    name: educational-platform-api
    runtime: node
    region: oregon
    plan: free
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: FROM_NAME
        value: Educational Platform
      - key: FROM_EMAIL
        value: noreply@educationalplatform.com
      - key: PAYMOB_API_KEY
        sync: false
      - key: PAYMOB_INTEGRATION_ID
        sync: false
      - key: PAYMOB_IFRAME_ID
        sync: false
      - key: PAYMOB_HMAC_SECRET
        sync: false
      - key: PAYMOB_SECRET_KEY
        sync: false
      - key: PAYMOB_PUBLIC_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
